const allCity = {
  currentCity : {
    "id": 96,
    "name": "济南",
    "pinyin": "jinan",
    "acronym": "jn",
    "onlineTime": "1298822400",
    "open": true,
    "rank": "B",
    "locationId": "370100",
    "position": {
      "lat": 36.682785,
      "lng": 117.0249634
    },
    "divisionStr": "",
    "originGeotagID": 0,
    "realLocationID": "370100",
    "provinceLocationID": "370000",
    "gisID": "370100",
    "chineseFullName": "济南市",
    "isHot": 0,
    "firstChar": "J",
    "originCityID": 0,
    "recommend": 1,
    "newIndex": 1,
    "endTime": "2000000000"
  },
  openCityList : [
    ["A", [
      {
        "id": 151,
        "name": "鞍山",
        "pinyin": "anshan",
        "acronym": "as",
        "rank": "C",
        "firstChar": "A"
      }, 
      {
        "id": 197,
        "name": "安庆",
        "pinyin": "anqing",
        "acronym": "anqing",
        "rank": "D",
        "firstChar": "A"
      }, 
      {
        "id": 238,
        "name": "安阳",
        "pinyin": "anyang",
        "acronym": "ay",
        "rank": "D",
        "firstChar": "A"
      }
    ]
  ],
  ["B", [{
    "id": 1,
    "name": "北京",
    "pinyin": "beijing",
    "acronym": "bj",
    "rank": "S",
    "firstChar": "B"
  }, {
    "id": 140,
    "name": "包头",
    "pinyin": "baotou",
    "acronym": "bt",
    "rank": "C",
    "firstChar": "B"
  }, {
    "id": 84,
    "name": "保定",
    "pinyin": "baoding",
    "acronym": "bd",
    "rank": "C",
    "firstChar": "B"
  },
  {
    "id": 297,
    "name": "百色",
    "pinyin": "baise",
    "acronym": "baise",
    "rank": "E",
    "firstChar": "B"
  }, {
    "id": 317,
    "name": "巴中",
    "pinyin": "bazhong",
    "acronym": "bazhong",
    "rank": "E",
    "firstChar": "B"
  }, {
    "id": 327,
    "name": "毕节",
    "pinyin": "bijiediqu",
    "acronym": "bijie",
    "rank": "E",
    "firstChar": "B"
  }, {
    "id": 332,
    "name": "保山",
    "pinyin": "baoshan",
    "acronym": "bs",
    "rank": "E",
    "firstChar": "B"
  }, {
    "id": 153,
    "name": "本溪",
    "pinyin": "benxi",
    "acronym": "benxi",
    "rank": "E",
    "firstChar": "B"
  }, {
    "id": 363,
    "name": "白银",
    "pinyin": "baiyin",
    "acronym": "by",
    "rank": "E",
    "firstChar": "B"
  }, {
    "id": 165,
    "name": "白山",
    "pinyin": "baishan",
    "acronym": "baishan",
    "rank": "E",
    "firstChar": "B"
  },
  {
    "id": 946,
    "name": "璧山",
    "pinyin": "bishan",
    "acronym": "bishan",
    "rank": "F",
    "firstChar": "B"
  }, {
    "id": 1257,
    "name": "拜城县",
    "pinyin": "baichengxian",
    "acronym": "baichengxian",
    "rank": "F",
    "firstChar": "B"
  }, {
    "id": 1237,
    "name": "巴楚县",
    "pinyin": "bachuxian",
    "acronym": "bachuxian",
    "rank": "F",
    "firstChar": "B"
  }, {
    "id": 602,
    "name": "宝应",
    "pinyin": "baoying",
    "acronym": "baoying",
    "rank": "F",
    "firstChar": "B"
  }, {
    "id": 681,
    "name": "北流",
    "pinyin": "beiliu",
    "acronym": "beiliu",
    "rank": "F",
    "firstChar": "B"
  }, {
    "id": 698,
    "name": "博爱",
    "pinyin": "boai",
    "acronym": "boai",
    "rank": "F",
    "firstChar": "B"
  },
  {
    "id": 1193,
    "name": "巴彦县",
    "pinyin": "bayanxian",
    "acronym": "bayanxian",
    "rank": "F",
    "firstChar": "B"
  }, {
    "id": 783,
    "name": "宝丰",
    "pinyin": "baofeng",
    "acronym": "baofeng",
    "rank": "F",
    "firstChar": "B"
  }, {
    "id": 852,
    "name": "博兴",
    "pinyin": "boxing",
    "acronym": "boxing",
    "rank": "F",
    "firstChar": "B"
  }, {
    "id": 887,
    "name": "泌阳",
    "pinyin": "biyang",
    "acronym": "biyang",
    "rank": "F",
    "firstChar": "B"
  }, {
    "id": 915,
    "name": "彬县",
    "pinyin": "binxian",
    "acronym": "binxian",
    "rank": "F",
    "firstChar": "B"
  }, {
    "id": 1165,
    "name": "北安市",
    "pinyin": "beianshi",
    "acronym": "beianshi",
    "rank": "F",
    "firstChar": "B"
  }, {
    "id": 952,
    "name": "博山",
    "pinyin": "boshan",
    "acronym": "boshan",
    "rank": "F",
    "firstChar": "B"
  }, {
    "id": 994,
    "name": "宾阳",
    "pinyin": "binyang",
    "acronym": "binyang",
    "rank": "F",
    "firstChar": "B"
  }, {
    "id": 1074,
    "name": "泊头市",
    "pinyin": "botou",
    "acronym": "botou",
    "rank": "F",
    "firstChar": "B"
  }, {
    "id": 1098,
    "name": "博罗县",
    "pinyin": "boluoxian",
    "acronym": "boluoxian",
    "rank": "F",
    "firstChar": "B"
  }, {
    "id": 1102,
    "name": "博白县",
    "pinyin": "bobaixian",
    "acronym": "bobaixian",
    "rank": "F",
    "firstChar": "B"
  }]
]
]}

export default allCity
